name: Build and deploy Python app to Azure Web App - mealbuddy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'           # 加速后续安装

      - name: Install dependencies into .python_packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .python_packages/lib/site-packages

      - name: Create deployable zip
        run: |
          mkdir -p out
          zip -r out/app.zip . \
            -x "venv/**" ".venv/**" ".git/**" ".github/**" \
               "**/__pycache__/**" "node_modules/**" "frontend/**" "*.log"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: out/app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-app
          path: out

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C69ED7E3B2AC421EB3AE9E0034412ACF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_72407E19198C4C108133C21175C21B45 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B2DF6B3DDE5844B2B62E92AEFF150360 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mealbuddy'
          slot-name: 'Production'
          package: out/app.zip
          clean: true
